background_color = 292D3E33
bar_color = EEFFFFdd
border_color = 3996c0ee
anchor = top right
margin = 30

overflow_background_color = 2E3440FF
overflow_bar_color = 88C0D0FF  
overflow_border_color = 4C566AFF
overflow_mode = wrap

; max = 100
timeout = 2000
width = 200
output_mode = all
border_size = 4
bar_padding = 6
