background {
    monitor = eDP-1
    path = /home/ephrem/.config/hypr/wallpaper/city.jpg
    # path = screenshot
    # path =
    blur_size = 4
    blur_passes = 3 # 0 disables blurring
    noise = 0.0117
    contrast = 1.3000 # Vibrant!!!
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    hide_cursor = true
    disable_loading_bar = true
}

input-field {
    monitor = eDP-1
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.64 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    	outer_color = rgba(255, 255, 255, 0.4)
	inner_color = rgba(0, 0, 0, 0.5)
	font_color = rgba(238, 75, 80, 0.9)
    fade_on_empty = true
    rounding = 22 
	placeholder_text = <span font_family="SpaceMono Nerd Font"><i>Password</i></span>
    hide_input = false
    position = 0, 50
    halign = center
    valign = bottom
fail_color = rgb(e6727a)
	fail_text = <span font_family="SpaceMono Nerd Font"><i>$FAIL <b>($ATTEMPTS)</b></i></span>
	fail_transition = 300
	shadow_passes = 2
	shadow_size = 2
	shadow_color = rgb(050505)
}


label {
	monitor =
	text = cmd[update:200] echo "$(date +'%-I:%M:%S')"
	color = rgba(c3ea59ee)
	font_size = 90
	font_family = VictorMono Nerd Font
	position = 0, 100
	halign = center
	valign = center
	shadow_passes = 2
	shadow_size = 3
	shadow_color = rgb(000000)
}

label {
	monitor =
	text = cmd[update:5000] echo "$(date +'%A, %b %d %Y')"
	color = rgba(ffee60cc)
	font_size = 60
	font_family = VictorMono Nerd Font
	position = 0, -40
	halign = center
	valign = center
	shadow_passes = 2
	shadow_size = 3
	shadow_color = rgb(000000)
}

label {
	monitor =
	text = cmd[update:9000] echo "$(ansiweather -l Arvada -s true -a false -p false -f 4 -u imperial)"
	color = rgba(44bddacc)
	font_size = 20
	font_family = SpaceMono Nerd Font
	position = 0, -200
	halign = center
	valign = center
	shadow_passes = 1
	shadow_size = 1
	shadow_color = rgb(000000)
}
