# Oh My Zsh
# Install Oh My Zsh!
if ! [[ -e ~/.oh-my-zsh ]]; then
  git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi
export ZSH="$HOME/.oh-my-zsh"

# Install Zsh Syntax Highlighting
# if ! [[ -e ~/.oh-my-zsh-custom/plugins/zsh-syntax-highlighting ]]; then
#     mkdir ~/.oh-my-zsh-custom/plugins
#     git clone git://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh-custom/plugins/zsh-syntax-highlighting
# fi

HISTSIZE=1000000
# SAVEHIST=100000
export HISTFILE="$HOME/.zsh_history"
HISTCONTROL=ignoreboth

# Enable Prompt Themes
autoload -U promptinit
promptinit
# Prompt Themes: use `prompt -l` to see themes
# To preview them: `prompt -p`
prompt fade

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
# Alias
[ -f "$ZDOTDIR/alias" ] && source "$ZDOTDIR/alias"

# Functions
[ -f "$ZDOTDIR/functions" ] && source "$ZDOTDIR/functions"

# Key Bindings
[ -f "$ZDOTDIR/bindings.zsh" ] && source "$ZDOTDIR/bindings.zsh"

# Completions
[ -f "$ZDOTDIR/completion.zsh" ] && source "$ZDOTDIR/completion.zsh"

# Options
[ -f "$ZDOTDIR/options.zsh" ] && source "$ZDOTDIR/options.zsh"

# Zprofile
[ -f "$ZDOTDIR/zprofile" ] && source "$ZDOTDIR/zprofile"

# LS COLORS
[ -f "$ZDOTDIR/lscolors.sh" ] && source "$ZDOTDIR/lscolors.sh"

# Export
[ -f "$ZDOTDIR/exports" ] && source "$ZDOTDIR/exports"

#export KEYTIMEOUT=1
#
# Theme
ZSH_THEME="robbyrussell"

# Plugins
# Install Function
# $1 is the name of the plugin
# $2 is the github url
# install_plugin() {
#     if [ ! -e $ZSH"custom/plugins/$1" ]
#     then
#       echo "cloning $2 into $ZSH""custom/plugins/$1"
#       sudo git clone $2 $ZSH"custom/plugins/$1"
#     fi
# }
#
# install_plugin "zsh-autosuggestions" "https://github.com/zsh-users/zsh-autosuggestions"
# install_plugin "zsh-completions" "https://github.com/zsh-users/zsh-completions"
# install_plugin "zsh-syntax-highlighting" "https://github.com/zsh-users/zsh-syntax-highlighting"

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  fast-syntax-highlighting
  zsh-history-substring-search
  zsh-fzf-history-search
  fzf-tab
)

source $ZSH/oh-my-zsh.sh

# STARSHIP
if hash starship 2>/dev/null; then
  eval "$(starship init zsh)"
fi
# Starship
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"

# FIXME: move it to alias
alias ls="eza"
