# Export
# XDG BASE DIR CONFIGURATION
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export  XDG_STATE_HOME="$HOME/.local/state"

[ -d "$XDG_CONFIG_HOME" ] || mkdir -m 0750 "$XDG_CONFIG_HOME"
[ -d "$XDG_CACHE_HOME" ]  || mkdir -m 0750 "$XDG_CACHE_HOME"
[ -d "$XDG_DATA_HOME" ]   || mkdir -m 0750 "$XDG_DATA_HOME"
[ -d "$XDG_STATE_HOME" ]  || mkdir -m 0750 "$XDG_STATE_HOME"


# Bootstrap .zshrc to ~/.config/zsh/.zshrc, any other zsh config files can also reside here
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Scripts Folder
export PATH="$XDG_CONFIG_HOME/scripts:$PATH"

# Editor
export EDITOR=nvim
export VISUAL=nvim
export LANG=en_US.UTF-8
export SUDO_EDITOR=nvim

# External Programs
# Oh My Zsh
# Install Oh My Zsh!
if ! [[ -e ~/.oh-my-zsh ]]; then
     git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi
export ZSH="$HOME/.oh-my-zsh"

# Install Zsh Syntax Highlighting
# if ! [[ -e ~/.oh-my-zsh-custom/plugins/zsh-syntax-highlighting ]]; then
#     mkdir ~/.oh-my-zsh-custom/plugins
#     git clone git://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh-custom/plugins/zsh-syntax-highlighting
# fi
# export TERM="xterm-256color"
export PATH="/var/lib/flatpak/exports/bin:$PATH"

# Starship
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

# OTHER PROGRAM PATHS
export PATH="/usr/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
# export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.npm/bin:$PATH"

# EMACS
export PATH=/usr/local/bin:/usr/bin:/bin:$HOME/.cargo/bin:$HOME/.local/bin:
# Ripgrep
export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/ripgreprc"

# Manpage
# export MANPAGER="less -R --use-color -Dd+r -Du+b"
# Use bat as man pager
# Alternatively use `batman`
export MANPAGER="sh -c 'awk '\''{ gsub(/\x1B\[[0-9;]*m/, \"\", \$0); gsub(/.\x08/, \"\", \$0); print }'\'' | bat -p -lman'"

# colored less + termcap vars
# export LESS="R --use-color -Dd+r -Du+b"
#export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
# export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
# export LESS_TERMCAP_me="$(printf '%b' '[0m')"
# export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
# export LESS_TERMCAP_se="$(printf '%b' '[0m')"
# export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
# export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
# export MANPAGER="nvim +Man!"
# export MANPAGER='less -s -M +Gg'
# export LESS_TERMCAP_mb=$'\e[1;31m'
# export LESS_TERMCAP_md=$'\e[1;36m'
# export LESS_TERMCAP_me=$'\e[0m'
# export LESS_TERMCAP_se=$'\e[0m'
# export LESS_TERMCAP_so=$'\e[1;44;33m'
# export LESS_TERMCAP_ue=$'\e[0m'
# export LESS_TERMCAP_us=$'\e[1;32m'
# export MANPAGER="less -MR+Gg"

# Setting VIMINIT Environment Variable
# Use `vimrc` from config directory
# export VIMINIT="$XDG_CONFIG_HOME/vim/vimrc"
#export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

# General Settings
# check `man zshoptions`
# Use Emacs Keybindings
# bindkey -e
# Go to folder path without using CD
setopt AUTO_CD
# Push the old directory onto the stack on cd.
setopt AUTO_PUSHD
# Do not store duplicates in the stack.
setopt PUSHD_IGNORE_DUPS
# Do not print the directory stack after pushd or popd.
setopt PUSHD_SILENT

# Default: Blank `pushd` goes to home
setopt PUSHD_TO_HOME

# Treat metacharcters as part of patterns for filename generation
setopt EXTENDED_GLOB
# Print error if no match found
setopt NOMATCH
setopt PROMPT_SUBST     # enable command substitution in prompt
setopt LIST_PACKED      # The completion menu takes less space.

setopt NOMATCH

# Do not show error
unsetopt BEEP
# setopt no_beep
# History Related
setopt APPENDHISTORY
setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.

# Remove extra blanks from each command added to history
setopt HIST_REDUCE_BLANKS

# Don't wait until shell exits to add commands to history
setopt INC_APPEND_HISTORY

# Wait 10 seconds wait if `rm *`
setopt RM_STAR_WAIT

# Allow comment with #
setopt INTERACTIVE_COMMENTS

# Spell Correction for Commands
setopt CORRECT
# But not for arguments
unsetopt CORRECT_ALL

# Make Alias Commands Distinct for Completion purpose
# By unsetting, substitute alias before completion
unsetopt COMPLETE_ALIASES

# When completing from the middle of a word, move the cursor to the end of the
# word;
unsetopt ALWAYS_TO_END

# Autoselect the first completion entry
setopt MENU_COMPLETE

# Show completion menu on successive tab press (menu_complete overrides)
setopt AUTO_MENU

# Automatically list choices on ambiguous completion.
setopt AUTO_LIST

# DEFAULT; will put / instead of space when autocomplete for param (ex ~D(tab)
# puts ~D/)
setopt auto_param_slash

# allow completion from within a word/phrase
# ex: completes to Desktop/ from Dktop with cursor before k)
setopt COMPLETE_IN_WORD


HISTSIZE=1000000
# SAVEHIST=100000
HISTFILE="$HOME/.zsh_history"
HISTCONTROL=ignoreboth

# TODO Modules
zmodload zsh/complist

# Command completion
# Use `compinstall` for interactive configuration
autoload -U compinit && compinit
autoload -U colors && colors
# Enable Prompt Themes
autoload -U promptinit
promptinit

# Prompt Themes: use `prompt -l` to see themes
# To preview them: `prompt -p`
prompt fade

# TODO Completion Style
# Syntax for zstyle; `zstyle <pattern> <style> <values>`
# Syntax for completion: `:completion:<function>:<completer>:<command>:<argument>:<tag>`
# Define completers
zstyle ':completion:*' completer _extensions _complete _approximate
zstyle ':completion:*' menu select
zstyle ':completion:*:*:kill:*' list-colors '=(#b) #([0-9]#)*( *[a-z])*=34=31=33'
zstyle ':completion:*' use-cache on
zstyle ':completion:' cache-path "$HOME/.cache/zsh/.zcompcache"
zstyle ':completion:*:parameters' list-colors '=*=1;35'
zstyle ':completion:*:builtins' list-colors '=*=1;34'
zstyle ':completion:*:aliases' list-colors '=*=1;33'
#zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:*:*:descriptions' format '%F{green}%d %f'
zstyle ':completion:*:*:*:*:corrections' format '%F{yellow}!- %d (errors: %e) -!%f'
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}no matches found %f'
zstyle ':completion:*:options' list-colors '=^(-- *)=34'
zstyle ':completion:*:*:-command-:*:*' group-order alias functions builtins commands
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
# Grouping
# zstyle ':completion:*' group-name ''
zstyle ':completion:*:*:-command-:*:*' group-order alias builtins functions commands
# Detailed file listing
zstyle ':completion:*' file-list all

# Alias
[ -f "$XDG_CONFIG_HOME/zsh/alias" ] && source "$XDG_CONFIG_HOME/zsh/alias"

# Functions
[ -f "$XDG_CONFIG_HOME/zsh/functions" ] && source "$XDG_CONFIG_HOME/zsh/functions"

# Key Bindings
[ -f "$XDG_CONFIG_HOME/zsh/keybinds" ] && source "$XDG_CONFIG_HOME/zsh/keybinds"

#export KEYTIMEOUT=1
#
# Theme
ZSH_THEME="robbyrussell"


# Plugins
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  fast-syntax-highlighting
  zsh-history-substring-search
  zsh-fzf-history-search
)

# Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Others Configuration

# Dircolors
export DIRCOLOR="$XDG_CONFIG_HOME/zsh/dircolors.conf"
if [[ -x "$(command -v dircolors)" && -f "$DIRCOLOR" ]]; then
  eval "$(dircolors -b "$DIRCOLOR")"
fi

# # This makes Zsh's tab completion respect your custom colors.
if [[ -n "$LS_COLORS" ]]; then
  zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
fi

# FZF Shell integrations
eval "$(fzf --zsh)"

# FZF settings
# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# FZF Configuration
if [[ $(command -v "fzf") ]]; then
  source $XDG_CONFIG_HOME/zsh/fzf.zsh
fi

# PYENV
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# STARSHIP
if hash starship 2>/dev/null; then
  eval "$(starship init zsh)"
  fi

# Bare Dotfiles
#alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME'


export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
