# Colors
# ---
# vim:ft=kitty

foreground #E0DEF4
background #191724
selection_foreground #eaeaea
selection_background #404040

cursor #E0DEF4
cursor_text_color #D8DEE9

# tab_bar_background #f6f8fa
# active_tab_foreground #24292f
# active_tab_background #ffffff
# inactive_tab_foreground #57606a
# inactive_tab_background #f6f8fa

# Black
color0 #26233A
color8 #26233A

# Red
color1 #EB6F92
color9 #EB6F92

# Green
color2  #9CCFD8
color10 #9CCFD8

# Yellow
color3  #F6C177
color11 #F6C177

# Blue
color4  #31748F
color12 #31748F

# Magenta
color5  #C4A7E7
color13 #C4A7E7

# Cyan
color6  #EBBCBA
color14 #EBBCBA

# White
color7  #E0DEF4
color15 #E0DEF4
