#!/bin/sh
####################
# General Settings #
####################
riverctl keyboard-layout en
# Touchpad Settings
# Get device name from riverctl list-inputs
riverctl input "pointer-1267-12981-ELAN06D4:00_04F3:32B5_Touchpad" tap enabled
riverctl input "pointer-1267-12981-ELAN06D4:00_04F3:32B5_Touchpad" accel-profile flat
riverctl input "pointer-1267-12981-ELAN06D4:00_04F3:32B5_Touchpad" accel-profile flat
riverctl input "pointer-1267-12981-ELAN06D4:00_04F3:32B5_Touchpad" natural-scroll enabled
riverctl input "pointer-1267-12981-ELAN06D4:00_04F3:32B5_Touchpad" disable-while-typing enabled
riverctl input "pointer-1267-12981-ELAN06D4:00_04F3:32B5_Touchpad" disable-while-trackpointing enabled
# Disable touchscreen
riverctl input "touch-1267-16936-ELAN901C:00_04F3:4228" events disabled

riverctl map-switch normal lid close "swaylock -f"

##########################
###### MY KEYBINDINGS ####
##########################
# Note: the "$mod" modifier is also known as Logo, GUI, Windows, Mod4, etc.
mod="Mod4"

# $mod+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal $mod Return spawn "alacritty"

# Run Rofi
riverctl map normal $mod D spawn "rofi -show drun"

# $mod+Q to close the focused view
riverctl map normal $mod Q close

# $mod+Shift+Q to exit river
riverctl map normal $mod+Shift E exit

# Powermenu
riverctl map normal $mod+Shift Q spawn "$HOME/.config/rofi/rofi-power.sh"
# Wifi
riverctl map normal $mod+Control W spawn "$HOME/.config/rofi/rofi-wifi.sh"
# Bluetooth
riverctl map normal $mod+Control B spawn "$HOME/.config/rofi/rofi-bluetooth.sh"
# Reload
riverctl map normal $mod+Control R spawn "$HOME/.config/river/init"
# Toggle waybar
riverctl map normal $mod B spawn "$HOME/.config/river/scripts/waybar"
# Lock
riverctl map normal $mod+Shift Z spawn "hyprlock"
# Clipboard
riverctl map normal $mod V spawn "cliphist list | rofi -dmenu -p 'Clipboard' -config $HOME/.config/rofi/regular.rasi | cliphist decode | wl-copy"
# swayidle-toggle
sig_1="pkill -SIGRTMIN+1 waybar"
riverctl map normal Super+Shift F11 spawn "$HOME/.config/river/scripts/swayidle-toggle.sh && $sig_1"

########################
# DEFAULT KEYBINDINGS #
#######################
# $mod+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# $mod+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# $mod+Period and Super+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# $mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# $mod+Return to bump the focused view to the top of the layout stack
#riverctl map normal $mod Return zoom

# $mod+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# $mod+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# $mod+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Alt H move left 100
riverctl map normal $mod+Alt J move down 100
riverctl map normal $mod+Alt K move up 100
riverctl map normal $mod+Alt L move right 100

# $mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Alt+Control H snap left
riverctl map normal $mod+Alt+Control J snap down
riverctl map normal $mod+Alt+Control K snap up
riverctl map normal $mod+Alt+Control L snap right

# $mod+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal $mod+Alt+Shift H resize horizontal -100
riverctl map normal $mod+Alt+Shift J resize vertical 100
riverctl map normal $mod+Alt+Shift K resize vertical -100
riverctl map normal $mod+Alt+Shift L resize horizontal 100

# $mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# $mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# $mod + Middle Mouse Button to toggle float
riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

# $mod+Space to toggle float
riverctl map normal $mod Space toggle-float

# $mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# $mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# $mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# $mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
  # Eject the optical drive (well if you still have one that is)
  riverctl map $mode None XF86Eject spawn 'eject -T'

  # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
  riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
  riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
  riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'

  # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext spawn 'playerctl next'

  # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
  riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
  riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

##########################
######  Tags    #########
##########################
# Tags
terminal_tag=$((1 << 0))
files_tag=$((1 << 1))
browser_tag=$((1 << 2))

riverctl rule-add --app-id "alacritty" tags $terminal_tag
riverctl rule-add --app-id "kitty" tags $terminal_tag
riverctl rule-add --app-id "ghostty" tags $terminal_tag

riverctl rule-add --app-id "dolphin" tags $files_tag

riverctl rule-add --app-id "firefox" tags $browser_tag
riverctl rule-add --app-id "librewolf" tags $browser_tag



for i in $(seq 1 9); do
  tags=$((1 << ($i - 1)))

  # $mod+[1-9] to focus tag [0-8]
  riverctl map normal $mod $i set-focused-tags $tags

  # $mod+Shift+[1-9] to tag focused view with tag [0-8]
  riverctl map normal $mod+Shift $i set-view-tags $tags

  # $mod+Control+[1-9] to toggle focus of tag [0-8]
  riverctl map normal $mod+Control $i toggle-focused-tags $tags

  # $mod+Shift+Control+[1-9] to toggle tag [0-8] of focused view
  riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# $mod+0 to focus all tags
# $mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

############################
##### River Configuration #######
############################
# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75
riverctl border-color-urgent #bf616a
riverctl border-width 1

# Set keyboard repeat rate
riverctl set-repeat 50 300
riverctl default-attach-mode bottom
riverctl focus-follow-cursor always
riverctl hide-cursor timeout 10000
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
riverctl xcursor-theme Adawita 24

##########################
######  Rules    #########
##########################
# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float
# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd
riverctl rule-add -app-id "firefox*" float
riverctl rule-add -app-id "polkit-kde-authentication-agent-1" float

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 2 -outer-padding 2 &

#######################
######## Autostart ####
#######################
source "$HOME/.config/river/environment"
riverctl spawn "/usr/libexec/polkit-kde-authentication-agent-1"
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
riverctl spawn "systemctl --user import-environment"
riverctl spawn "swaybg -i ~/Pictures/berserk.png"
riverctl spawn "waybar -c /home/ephrem/.config/waybar/riverconfig.jsonc -s /home/ephrem/.config/waybar/river.css"
riverctl spawn wlsunset
riverctl spawn mpd
#riverctl spawn "swayidle -w"
riverctl spawn "swayidle -w \
    timeout 300 '[ \"$(playerctl status 2>/dev/null)\" != \"Playing\" ] && swaylock -f' \
    timeout 600 '[ \"$(playerctl status 2>/dev/null)\" != \"Playing\" ] && systemctl suspend' \
    resume 'riverctl focus-output next' \
    before-sleep 'swaylock -f'"
# riverctl spawn /usr/lib/notification-daemon-1.0/notification-daemon
#riverctl spawn dunst
river spawn mako
river spawn hyprlock
# riverctl spawn  "deadd-notification-center"
riverctl spawn "nm-applet --indicator"
riverctl spawn "foot --server"
riverctl spawn "blueman-applet"
riverctl spawn "emacs --daemon"
riverctl spawn "/usr/lib/kdeconnectd"
#riverctl spawn "/usr/bin/kdeconnect-indicator"
riverctl spawn "swaync"
# Clipboard
riverctl spawn "wl-clipboard"
riverctl spawn "wl-paste --type text --watch cliphist store"  #Stores only text data
riverctl spawn "wl-paste --type image --watch cliphist store" #Stores only image data
