####################
# Default Keybinds
####################
bindsym $mod+Return exec $term # Open Terminal
bindsym $mod+d exec $menu # Open Menu  
bindsym $mod+Escape $power # Exit options 1 
bindsym $mod+Shift+q exec $power # Exit Options 2
bindsym $mod+Shift+f exec $file # Open Filebrowser
bindsym $mod+Shift+z exec $lock # Lockscreen
bindsym $mod+Shift+w exec $wifi # Open Wifi Menu  
bindsym $mod+Shift+v exec $clipboard # Open Clipboard
bindsym $mod+Control+w exec $bluetooth # Open Bluetooth
bindsym $mod+Shift+o exec $emoji # Open Emoji Options 
bindsym $mod+Control+k exec $keys # Open Shortcuts 
bindsym $mod+Control+0 exec $calc # Open Calculator

