[main]
shell=/usr/bin/zsh -i
include=~/.config/foot/themes/nord
font=Berkeley Nerd Font:pixelsize=14
font-bold=Berkeley Nerd Font:pixelsize=14:weight=bold
font-italic=Berkeley Nerd Font:pixelsize=14:slant=italic
font-bold-italic=Berkeley Nerd Font:pixelsize=14
font-size-adjustment=0.8
#font=JetBrainsMono Nerd Font Mono:pixelsize=14
#font-italic=JetBrainsMono Nerd Font:style=SemiBold Italic:pixelsize=14
#font-bold=JetBrainsMono Nerd Font:style=Bold:pixelsize=11
#font-size-adjustment=0.5
letter-spacing=1px
line-height=18px
#underline-thickness=2
bold-text-in-bright=yes
initial-window-mode=windowed
#initial-window-size-chars=80x32
title="Foot"
locked-title=no
selection-target=both
#dpi-aware=yes
pad=10x10 center
[cursor]
style=block
unfocused-style=hollow
blink=yes
blink-rate=500
#color= ff0000 00ff00
beam-thickness=1.5
#underline-thickness=2px
[bell]
urgent=yes
notify=yes
visual=yes
[scrollback]
lines=1000
multiplier=4.0
indicator-position=relative
[mouse]
hide-when-typing=yes
