
# output=<not set>
font=Berkeley Nerd Font:size=12:weight=bold
use-bold=no
dpi-aware=no
placeholder="Application"
prompt="> " 
icon-theme=kora 
icons-enabled=yes
hide-before-typing=no
# fields=filename,name,generic
# password-character=*
match-mode=exact
sort-result=yes
match-counter=no
fuzzy=yes
# show-actions=no
# terminal=$TERMINAL -e  # Note: you cannot actually use environment variables here
# launch-prefix=<not set>
anchor=center
lines=15
width=40
tabs=8
horizontal-pad=40
vertical-pad=20
inner-pad=20
image-size-ratio=0.5
letter-spacing=1
# line-height=<use font metrics>
line-height=20
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
background=2E3440FF
text=D8DEE9FF 
prompt=D8DEE9FF
placeholder=D8DEE922
input=D8DEE9FF
match=D8DEE9FF
selection=81A1C1FF
selection-text=D8DEE9FF
selection-match=D8DEE9FF
border=88C0D0FF

[border]
width=2
radius=10

[dmenu]
# mode=text  # text|index
# exit-immediately-if-empty=no

