#! /bin/sh

#--------------------Startup------------#
pgrep -x sxhkd >/dev/null || sxhkd &
nm-applet &
picom &
redshift &
#kdeconnect-app &
polybar &
mpd &
export QT_QPA_PLATFORMTHEME=kde

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9

feh --bg-fill ~/Pictures/wallpapers/0002.jpg

bspc config border_width 1
bspc config window_gap 0
bspc config top_padding 10

bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#a9b1d6"
bspc config active_border_color "#c0caf5"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a firefox desktop='^1' follow = on
bspc rule -a vlc desktop='^4' follow = on
bspc rule -a kdeconnect-app desktop='^5' follow = on
bspc rule -a telegram-desktop desktop='^7'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "mpv" desktop='^3' state=floating focus=on follow=on
