syntax on
filetype on
filetype indent on
colorscheme slate

set autoindent
set autowrite
set autoread
set cursorline
set cursorcolumn
set encoding=utf-8
set hidden
set history=1000
set hlsearch
set incsearch
set ignorecase
set mouse=a
set nocompatible
set nospell
set noswapfile
set number
set shiftwidth=4
set showmatch
set smartindent
set softtabstop=4
set spelllang=en_us
set splitbelow
set splitright
set tabstop=4
set ttyfast
set undolevels=999
set wrap

" KEYMAPPINGS
let mapleader=" "
let maplocalleader=","

" General
nnoremap <leader>q :quit<CR>
nnoremap <leader>qq :qall<CR>
nnoremap <leader>h :h option-list<CR>
nnoremap <leader>r :source ~/.config/vim/vimrc<CR>
" Buffer management
nnoremap <tab> :bn<CR>
nnoremap <S-tab> :bp<CR>
nnoremap <leader>bd :bd<CR>
" Window management
nnoremap <leader>wv :vsplit<CR>
nnoremap <leader>wh :split<CR>
nnoremap <leader>wq :close<CR>
nnoremap <leader>wq :close<CR>
" Insert Mode
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-h> <Left>
inoremap <C-l> <Right>


" OTHERS
" Remove trailing whitespace on write
if has("autocmd")
    autocmd BufWritePre * %s/\s\+$//e
endif
