syntax on
filetype on
filetype indent on
colorscheme slate

set autoindent
set autowrite
set autoread
set clipboard=unnamedplus "Linux
set nobackup
set cursorline
set cursorcolumn
set encoding=utf-8
set hidden
set history=1000
set hlsearch
set incsearch
set ignorecase
set mouse=a
set nocompatible
set nospell
set noswapfile
set number
set shiftwidth=4
set showmatch
set smartcase
set smartindent
set softtabstop=4
set spelllang=en_us
set splitbelow
set splitright
set tabstop=4
set ttyfast
set undolevels=999
set wrap

" KEYMAPPINGS
let mapleader=" "
let maplocalleader=","

" General
nnoremap <leader>q :quit<CR>
nnoremap <leader>qq :qall<CR>
nnoremap <leader>h :h option-list<CR>
nnoremap <leader>r :source ~/.config/vim/vimrc<CR>
" Buffer management
nnoremap <tab> :bn<CR>
nnoremap <S-tab> :bp<CR>
nnoremap <leader>bd :bd<CR>
" Window management
nnoremap <leader>wv :vsplit<CR>
nnoremap <leader>wh :split<CR>
nnoremap <leader>wq :close<CR>

" Insert Mode
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-h> <Left>
inoremap <C-l> <Right>

" Disable the spacebar key's default behavior in Normal and Visual modes
nnoremap <Space> <Nop>
vnoremap <Space> <Nop>

" Allow moving the cursor through wrapped lines with j, k
nnoremap <expr> k v:count == 0 ? 'gk' : 'k'
nnoremap <expr> j v:count == 0 ? 'gj' : 'j'

" clear highlights
nnoremap <leader>nh :noh<CR>


" save file
nnoremap <leader>ww :w<CR>

" save file without auto-formatting
nnoremap <leader>sn :noautocmd w<CR>

" tabs
nnoremap <leader>to :tabnew<CR>
nnoremap <leader>tx :tabclose<CR>
nnoremap <leader>tn :tabn<CR>
nnoremap <leader>tp :tabp<CR>


" toggle line wrapping
nnoremap <leader>lw :set wrap!<CR>


" Open file explorer
noremap <silent> <leader>e :Lex<CR>


" OTHERS
" Remove trailing whitespace on write
if has("autocmd")
	autocmd BufWritePre * %s/\s\+$//e
endif

" Netrw
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25
" Use 'l' instead of <CR> to open files
augroup netrw_setup | au!
	au FileType netrw nmap <buffer> l <CR>
augroup END
