syntax on
filetype on
filetype indent on
colorscheme slate

set autowrite
set autoread
set cursorline
set cursorcolumn
set encoding=utf-8
set hidden
set hlsearch
set incsearch
set mouse=a
set nocompatible
set nospell
set noswapfile
set number
set smartindent
set softtabstop=4
set spelllang=en_us
set tabstop=4
set ttyfast
set wrap

" KEYMAPPINGS
let mapleader=" "
let maplocalleader=","

" General
nnoremap <leader>q :quit<CR>
nnoremap <leader>qq :qall<CR>
nnoremap <leader>h :h option-list<CR>
" Buffer management
nnoremap <tab> :bn<CR>
nnoremap <S-tab> :bp<CR>
nnoremap <leader>bd :bd<CR>
" Window management
nnoremap <leader>wv :vsplit<CR>
nnoremap <leader>wh :split<CR>
nnoremap <leader>wq :close<CR>
nnoremap <leader>wq :close<CR>
" Insert Mode
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-h> <Left>
inoremap <C-l> <Right>
