#!/usr/bin/env bash

set -euo pipefail

mapfile -t flatpak_packages <"./flatpak.packages"

install_flatpak_package() {

  [[ $# -eq 0 ]] && echo "No packages to install." && return

  for package in "$@"; do
    if flatpak list --app | grep -q "$package"; then
      echo "$package already installed!"
    else
      echo "Installing $package..."
      flatpak install -y "$package"
    fi
  done

}

install_flatpak_package "${flatpak_packages[@]}"
