#!/usr/bin/env bash

package_list=(
vivid
atuin
fzf
)

if command -v apt &> /dev/null; then
  package_manager=apt
elif command -v yum &> /dev/null; then
  package_manager=yum
elif command -v dnf &> /dev/null; then
  package_manager=dnf
elif command -v pacman &> /dev/null; then
  package_manager=pacman
elif command -v zypper &> /dev/null; then
  package_manager=zypper
else
  echo "No common package manager found."
fi

echo "You are using ${package_manager} as a package manager."

if [[ $package_manager == 'zypper' ]]; then
for package in "${package_list[@]}"; do
  sudo zypper in "$package"
# echo $package
done 2> /dev/null
elif [[ $package_manager == 'pacman' ]]; then
  for package in "${package_list[@]}"; do
    sudo pacman -S "$package"
    done 2> /dev/null
fi
