#!/usr/bin/env bash

FILE="packages.txt"

if [[ ! -f "$FILE" ]]; then
  echo "Error: File '$FILE' not found!"
  exit 1
fi

# package_list=()
# while IFS= read -r package; do
#   package_list+=("$package")
#   # echo $package
# done <"$FILE"

# Read packages into array, ignoring empty lines and comments
mapfile -t package_list < <(grep -Ev '^\s*#|^\s*$' "$FILE")

if [[ ${#package_list[@]} -eq 0 ]]; then
  echo "No packages found in $FILE."
  exit 1
fi

# Check for package manager
if command -v apt &>/dev/null; then
  package_manager=apt
elif command -v yum &>/dev/null; then
  package_manager=yum
elif command -v dnf &>/dev/null; then
  package_manager=dnf
elif command -v pacman &>/dev/null; then
  package_manager=pacman
elif command -v zypper &>/dev/null; then
  package_manager=zypper
else
  echo "No package manager found."
  exit 1
fi

echo "You are using ${package_manager} as a package manager."
echo "Started Installation ..."
if [[ $package_manager == 'zypper' ]]; then
  sudo zypper refresh
  for package in "${package_list[@]}"; do
	echo "Installing $package ..."
	sudo zypper --non-interactive install "$package"
  done
elif [[ $package_manager == 'pacman' ]]; then
  sudo pacman -Sy --noconfirm
  for package in "${package_list[@]}"; do
	echo "Installing $package ..."
	sudo pacman -S --noconfirm "$package"
  done
elif [[ $package_manager == 'dnf' ]]; then
  for package in "${package_list[@]}"; do
	sudo dnf install -y "$package"
  done
elif [[ $package_manager == 'apt' ]]; then
  sudo apt update -y
  for package in "${package_list[@]}"; do
	echo "Installing $package ..."
	sudo apt install -y "$package"
  done
fi
echo "Finished!!!"
