# Basic 
# The directory to store the downloaded file.
dir=${HOME}/Downloads
# Save error/unfinished downloads to FILE on exit.
save-session=${HOME}/.aria2/aria2.session
# Save error/unfinished downloads to a file specified by --save-session option every SEC seconds. If 0 is given, file will be saved only when aria2 exits. Default: 0
save-session-interval=60
# Set the maximum number of parallel downloads for every queue item. See also the --split option. Default: 5
max-concurrent-downloads=5
# Continue downloading a partially downloaded file.
continue=true
# Set max overall download speed in bytes/sec. 0 means unrestricted. Default: 0
max-overall-download-limit=0
# Set max download speed per each download in bytes/sec. 0 means unrestricted. Default: 0
max-download-limit=0
# Make aria2 quiet (no console output). Default: false
quiet=false
file-allocation=falloc

log-level=notice

check-integrity=true
# The number of connections per server (can be useful for faster downloads)
split=5

# Retry download attempts
max-tries=10
retry-wait=5

# Timeout settings
timeout=60
connect-timeout=60
# Continue downloads from partially downloaded files
continue=true
# Rename file name if the same file already exists. This option works only in HTTP(S)/FTP download. Default: true
auto-file-renaming=true
# Overwrite existing files
allow-overwrite=true

# Use IPv4 or IPv6 exclusively if necessary
disable-ipv6=false

# HTTP/FTP
max-connection-per-server=4

# BitTorrent
# Enable BitTorrent downloads
enable-bittorrent=true
bt-max-peers=50
listen-port=49164
max-overall-upload-limit=3K
follow-torrent=mem

