# Nord
[colors]
[colors.primary]
foreground="#D8DEE9"
background="#2E3440"
[colors.normal]
black = "#2E3440"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#5E81AC"
magenta = "#B48EAD"
cyan = "#8FBCBB"
white = "#D8DEE9"
[colors.bright]
black = "#3B4252"
red = "#D32F2F"
green = "#388E3C"
yellow = "#ebcb8b"
blue = "#1976D2"
magenta = "#7B1FA2"
cyan = "#0097A7"
white = "#FAFAFA"
