
# Nord
[colors]
[colors.primary]
foreground="#D8DEE9"
background="#2E3440"
[colors.normal]
black = "#4C566A"
red = "#BF616A"
green = "#a3be8c" 
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"
[colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a4be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"

