# My Nord
[colors]
[colors.primary]
foreground="#ECEFF4"
background="#2E3440"

[colors.normal]
black = "#2E3440"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#5E81AC"
magenta = "#B48EAD"
cyan = "#8FBCBB"
white = "#D8DEE9"

[colors.bright]
black = "#272C36"
red = "#D32F2F"
yellow = "#ECBE7B"
green = "#388E3C"
blue = "#81A1C1"
magenta = "#7B1FA2"
cyan = "#9987A7"
white = "#FAFAFA"
