#!/usr/bin/env bash

# launcher=$(cat $HOME/.config/ml4w/settings/launcher)
launcher=rofi
if [ "$launcher" == "walker" ]; then
  $HOME/.config/walker/launch.sh -m clipboard -N -H
else
  case $1 in
	d)
	  selected=$(cliphist list | rofi -dmenu -replace -config ~/.config/rofi/config-clipboard.rasi)
	  [ -z "$selected" ] && exit 0
	  echo "$selected" | cliphist delete
	  ;;
	w)
	  cliphist wipe
	  ;;
	*)
	  selected=$(cliphist list | rofi -dmenu -replace -config ~/.config/rofi/config-clipboard.rasi)
	  [ -z "$selected" ] && exit 0
	  echo "$selected" | cliphist decode | wl-copy
	  ;;
  esac
fi
