#! /usr/bin/env bash

walldir="$HOME/Pictures/nord"
lines=4
columns=7
icons_size=256

theme="listview { lines: ${lines}; columns: ${columns}; cycle:true; spacing:5px;}
	  element { padding:0px; margin:0px; }
	  element-icon { size: ${icons_size}px; }
	  element-text { enabled:false; }"

export PREVIEW=true
selected=$(find "$walldir" -type f |
  while read -r A; do echo -en "$A\x00icon\x1f$A\n"; done |
  rofi -dmenu \
	-show-icons \
	-p "Wallpaper" \
	-theme "$HOME/.config/rofi/config-change-wall.rasi" \
	-theme-str "$theme")

#cp "$selected" ~/.config/wall.png &&
if [ -z "$selected" ]; then
  exit 1
else
  awww img "$selected" \
	--transition-type=any \
	--transition-step=60 \
	--transition-fps=60 \
	--transition-duration=.7

  notify-send -i "$SELECTED" "󰸉 Wallpaper Changed"
# wal -n -e -a 80 -i "$HOME/.config/wall.png" && swaync-client -rs
fi
